export const estadosBR: { estado: string; identificador: number }[] = [
  { estado: 'Acre', identificador: 12 },
  { estado: 'Rondônia', identificador: 11 },
  { estado: 'Amazonas', identificador: 13 },
  { estado: 'Roraima', identificador: 14 },
  { estado: 'Pará', identificador: 15 },
  { estado: 'Amapá', identificador: 16 },
  { estado: 'Tocantins', identificador: 17 },
  { estado: 'Maranhão', identificador: 21 },
  { estado: 'Piauí', identificador: 22 },
  { estado: 'Ceará', identificador: 23 },
  { estado: 'Rio Grande do Norte', identificador: 24 },
  { estado: 'Paraíba', identificador: 25 },
  { estado: 'Pernambuco', identificador: 26 },
  { estado: 'Alagoas', identificador: 27 },
  { estado: 'Sergipe', identificador: 28 },
  { estado: 'Bahia', identificador: 29 },
  { estado: 'Minas Gerais', identificador: 31 },
  { estado: 'Espiríto Santo', identificador: 32 },
  { estado: 'Rio de Janeiro', identificador: 33 },
  { estado: 'São Paulo', identificador: 35 },
  { estado: 'Paraná', identificador: 41 },
  { estado: 'Santa Catarina', identificador: 42 },
  { estado: 'Rio Grande do Sul', identificador: 43 },
  { estado: 'Mato Grosso do Sul', identificador: 50 },
  { estado: 'Mato Grosso', identificador: 51 },
  { estado: 'Goiás', identificador: 52 },
  { estado: 'Distrito Federal', identificador: 53 },
]
